"""Italian country names -> ISO 3166-1 alpha-2. Generated from Wikidata
(items with P297 and their Italian label), plus the forms the CEI edition
uses; see docs/superpowers/plans/2026-10-01-gazetteer.md, Task 1."""

COUNTRY_IT = {
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "DZ",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antartide": "AQ",
    "Antigua e Barbuda": "AG",
    "Antille Olandesi": "AN",
    "Arabia Saudita": "SA",
    "Argentina": "AR",
    "Armenia": "AM",
    "Aruba": "AW",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaigian": "AZ",
    "Bahamas": "BS",
    "Bahrein": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belgio": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermuda": "BM",
    "Bhutan": "BT",
    "Bielorussia": "BY",
    "Bolivia": "BO",
    "Bosnia ed Erzegovina": "BA",
    "Botswana": "BW",
    "Brasile": "BR",
    "Brunei": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cambogia": "KH",
    "Camerun": "CM",
    "Canada": "CA",
    "Capo Verde": "CV",
    "Ciad": "TD",
    "Cile": "CL",
    "Cina": "CN",
    "Cipro": "CY",
    "Città del Vaticano": "VA",
    "Colombia": "CO",
    "Comore": "KM",
    "Corea del Nord": "KP",
    "Corea del Sud": "KR",
    "Costa Rica": "CR",
    "Costa d'Avorio": "CI",
    "Croazia": "HR",
    "Cuba": "CU",
    "Curaçao": "CW",
    "Danimarca": "DK",
    "Diego Garcia": "DG",
    "Dominica": "DM",
    "Ecuador": "EC",
    "Egitto": "EG",
    "El Salvador": "SV",
    "Emirati Arabi Uniti": "AE",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Eswatini": "SZ",
    "Etiopia": "ET",
    "Figi": "FJ",
    "Filippine": "PH",
    "Finlandia": "FI",
    "Francia": "FR",
    "Fær Øer": "FO",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Georgia del Sud e isole Sandwich meridionali": "GS",
    "Germania": "DE",
    "Ghana": "GH",
    "Giamaica": "JM",
    "Giappone": "JP",
    "Gibilterra": "GI",
    "Gibuti": "DJ",
    "Giordania": "JO",
    "Gran Bretagna": "GB",
    "Grecia": "GR",
    "Grenada": "GD",
    "Groenlandia": "GL",
    "Guadalupa": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guernsey": "GG",
    "Guinea": "GN",
    "Guinea Equatoriale": "GQ",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Guyana francese": "GF",
    "Haiti": "HT",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IQ",
    "Irlanda": "IE",
    "Islanda": "IS",
    "Isola Clipperton": "CP",
    "Isola Norfolk": "NF",
    "Isola di Natale": "CX",
    "Isole Cayman": "KY",
    "Isole Cocos": "CC",
    "Isole Cook": "CK",
    "Isole Falkland": "FK",
    "Isole Heard e McDonald": "HM",
    "Isole Marianne Settentrionali": "MP",
    "Isole Marshall": "MH",
    "Isole Pitcairn": "PN",
    "Isole Salomone": "SB",
    "Isole Vergini Britanniche": "VG",
    "Isole Vergini degli Stati Uniti": "VI",
    "Isole minori esterne degli Stati Uniti d'America": "UM",
    "Isole Åland": "AX",
    "Israele": "IL",
    "Italia": "IT",
    "Jugoslavia": "YU",
    "Kazakistan": "KZ",
    "Kenya": "KE",
    "Kirghizistan": "KG",
    "Kiribati": "KI",
    "Kosovo": "XK",
    "Kuwait": "KW",
    "Laos": "LA",
    "Lesotho": "LS",
    "Lettonia": "LV",
    "Libano": "LB",
    "Liberia": "LR",
    "Libia": "LY",
    "Liechtenstein": "LI",
    "Lituania": "LT",
    "Lussemburgo": "LU",
    "Macao": "MO",
    "Macedonia del Nord": "MK",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldive": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marocco": "MA",
    "Martinica": "MQ",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Messico": "MX",
    "Moldavia": "MD",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Montserrat": "MS",
    "Mozambico": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "Niue": "NU",
    "Norvegia": "NO",
    "Nuova Caledonia": "NC",
    "Nuova Zelanda": "NZ",
    "Olanda": "NL",
    "Oman": "OM",
    "Paesi Bassi": "NL",
    "Paesi Bassi caraibici": "BQ",
    "Pakistan": "PK",
    "Palau": "PW",
    "Panama": "PA",
    "Papua Nuova Guinea": "PG",
    "Paraguay": "PY",
    "Perù": "PE",
    "Polinesia francese": "PF",
    "Polonia": "PL",
    "Porto Rico": "PR",
    "Portogallo": "PT",
    "Principato di Monaco": "MC",
    "Qatar": "QA",
    "Regno Unito": "GB",
    "Regno dei Paesi Bassi": "NL",
    "Repubblica Ceca": "CZ",
    "Repubblica Centrafricana": "CF",
    "Repubblica Democratica Tedesca": "DD",
    "Repubblica Democratica del Congo": "CD",
    "Repubblica Dominicana": "DO",
    "Repubblica del Congo": "CG",
    "Riunione": "RE",
    "Romania": "RO",
    "Ruanda": "RW",
    "Russia": "RU",
    "Sahara Occidentale": "EH",
    "Saint Kitts e Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Vincent e Grenadine": "VC",
    "Saint-Barthélemy": "BL",
    "Saint-Martin": "MF",
    "Saint-Pierre e Miquelon": "PM",
    "Samoa": "WS",
    "Samoa Americane": "AS",
    "San Marino": "SM",
    "Sant'Elena, Ascensione e Tristan da Cunha": "SH",
    "Sark": "CQ",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Sint Maarten": "SX",
    "Siria": "SY",
    "Slovacchia": "SK",
    "Slovenia": "SI",
    "Somalia": "SO",
    "Spagna": "ES",
    "Sri Lanka": "LK",
    "Stati Federati di Micronesia": "FM",
    "Stati Uniti": "US",
    "Stati Uniti d’America": "US",
    "Stato di Palestina": "PS",
    "Sudafrica": "ZA",
    "Sudan": "SD",
    "Sudan del Sud": "SS",
    "Suriname": "SR",
    "Svalbard e Jan Mayen": "SJ",
    "Svezia": "SE",
    "Svizzera": "CH",
    "São Tomé e Príncipe": "ST",
    "Tagikistan": "TJ",
    "Tailandia": "TH",
    "Taiwan": "TW",
    "Tanzania": "TZ",
    "Terre Australi e Antartiche Francesi": "TF",
    "Territorio Britannico dell'Oceano Indiano": "IO",
    "Territorio fiduciario delle Isole del Pacifico": "PC",
    "Timor Est": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad e Tobago": "TT",
    "Tunisia": "TN",
    "Turchia": "TR",
    "Turkmenistan": "TM",
    "Turks e Caicos": "TC",
    "Tuvalu": "TV",
    "Ucraina": "UA",
    "Uganda": "UG",
    "Ungheria": "HU",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Venezuela": "VE",
    "Viet Nam": "VN",
    "Vietnam": "VN",
    "Wallis e Futuna": "WF",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",
    "isola Bouvet": "BV",
    "isola di Man": "IM",
    "regione del Trattato Antartico": "AQ",
}
