#!/usr/bin/env python3
"""Extract the saints and blessed each current eulogy commemorates (Latin editio altera 2004).

Each person is a Latin nominative name without honorific, with where it is
printed: the eulogy's text, or its nth footnote. Subjects come from
i18n/la.json, companions from the footnote lists and from the names at the
head of the text; data/persons_curated.json replaces a eulogy's extraction.
No text is stored. See docs/superpowers/specs/2026-10-08-persons-design.md.

  data/persons.json          {editions: {edition: {id: [{name, where}]}}}
  docs/persons-report.md     counts and what to review

Usage:
  python3 extract_persons.py /path/to/martyrology-texts [repo_root]

Standard library only.
"""

import json
import re
import sys
from pathlib import Path

from extract_typology import latin_texts, load_texts
from gazetteer_text import fold
from mentions_text import find_person
from persons_text import (WORD, _genitive_ending, footnote_names, full_variant, name_key, nominative, person_key,
                          subject_names, text_companions, without_parentheses)

EDITION = "martyrologium_romanum_2004"
COMMENT = ("The saints and blessed each eulogy commemorates, by edition: the Latin nominative name "
           "(honorific-free) and where it is printed, the text or the eulogy's nth footnote. Generated by "
           "scripts/extract_persons.py; see docs/superpowers/specs/2026-10-08-persons-design.md. "
           "Draft pending committee review.")


def build_lexicon(subjects, footnotes):
    """Every word of the known names, by name_key: the vocabulary nominatives are checked against."""
    lex = {}
    names = [n for mrid, s in subjects.items() for n in subject_names(mrid, s)]
    names += [n for notes in footnotes.values() for f in notes for n in footnote_names(f["text"])[0]]
    for n in names:
        for w in n.split():
            if w[:1].isupper():
                lex.setdefault(name_key(w), w)
    return lex


def _same_person(a, b):
    """One name is the other with more words ("Rosalia Clotildis a Sancta Pelagia Bes")."""
    x, y = name_key(a).split(), name_key(b).split()
    n = min(len(x), len(y))
    return n > 0 and x[:n] == y[:n]


# The other name printed right after a person in the text: "Mamántis seu Mamétis".
VARIANT_AFTER = re.compile(r"\s*,?\s*(?:seu|vel|sive)\s+((?:[^\W\d_][\w'’\-]*)(?:\s+[^\W\d_][\w'’\-]*)*)")


def text_variants(text, name, lexicon):
    """A text person's other name printed right after them, as a whole nominative name, and
    whether one is printed but could not be read (a genitive the lexicon does not know). The
    variant's capitalized words only; an undeclined word ("Cacciafronte") is taken as printed."""
    found = find_person(text or "", name)
    if not found:
        return [], False
    m = VARIANT_AFTER.match(text, found[0][1])
    if not m:
        return [], False
    words = []
    for w in m.group(1).split():
        if not w[:1].isupper():
            break
        nom = nominative(w, lexicon)
        if nom is None and _genitive_ending(name_key(w)):
            return [], True
        words.append(nom or w)
    return ([full_variant(name, " ".join(words))] if words else []), False


def _with_also(p, variants):
    """The person with `variants` added to `also`, in order, without repeats (by name_key, the
    first spelling kept) or their own name; keys in the order name, n, also, where."""
    seen, also = {name_key(p["name"])}, []
    for v in [*p.get("also", []), *variants]:
        if name_key(v) not in seen:
            seen.add(name_key(v))
            also.append(v)
    out = {k: v for k, v in p.items() if k not in ("also", "where")}
    if also:
        out["also"] = also
    out["where"] = p["where"]
    return out


def eulogy_persons(mrid, subject, text, footnotes, lexicon, curated):
    if mrid in curated:
        return [dict(p) for p in curated[mrid]], {"uncertain": [], "skipped": [], "printed_twice": [],
                                                  "variants_unread": [], "socii_without_names": False}
    persons = []
    first = {}  # name_key -> where the name was first listed
    count = {}  # name_key -> the persons of that name so far
    listed = {}  # (name_key, footnote) -> its occurrences in that footnote's list so far
    holder = {}  # name_key -> the position of the first person of that name
    subjects = subject_names(mrid, subject)

    def add(name, where, marked=False, also=()):
        # A fuller or shorter form of a subject is the subject, in the subject's form.
        if any(_same_person(name, s) for s in subjects if s != name):
            return
        key = name_key(name)
        if where == "text":
            same = key in first and not marked  # named again in the text, unless marked ("Theodori alterius")
        else:
            here = (key, where["footnote"])
            listed[here] = listed.get(here, 0) + 1
            # A name listed before (the text, an earlier footnote) is that person again the first time
            # this list names it, unless marked ("alius Felix"); any other occurrence in one list is
            # another person of that name.
            same = key in first and first[key] != where and listed[here] == 1 and not marked
        if same:
            if also and key in holder:
                persons[holder[key]] = _with_also(persons[holder[key]], also)  # the other names follow him
            return
        first.setdefault(key, where)
        count[key] = count.get(key, 0) + 1
        p = {"name": name}
        if count[key] > 1:
            p["n"] = count[key]
        p["where"] = where
        holder.setdefault(key, len(persons))
        persons.append(_with_also(p, also))

    for n in subjects:
        add(n, "text")
    uncertain, skipped, printed_twice, unread_text = [], [], [], []  # unread_text: text and footnotes
    socii = mrid.endswith("-et-socii")
    if socii:
        marks, tvars = [], {}
        names, uncertain = text_companions(text or "", lexicon, marked=marks, variants=tvars, unread=unread_text)
        for i, n in enumerate(names):
            add(n, "text", marked=i in marks, also=[full_variant(n, v) for v in tvars.get(i, [])])
    for i, f in enumerate(footnotes, start=1):
        marks, fvars = [], {}
        names, bad = footnote_names(f["text"], printed_twice=printed_twice, marked=marks, variants=fvars,
                                    unread=unread_text)
        skipped += bad
        for j, n in enumerate(names):
            add(n, {"footnote": i}, marked=j in marks, also=[full_variant(n, v) for v in fvars.get(j, [])])
    # The other name printed right after a person in the text ("Kingae seu Cunegundis").
    variants_unread = list(dict.fromkeys(unread_text))
    for i, p in enumerate(persons):
        if p["where"] != "text":
            continue
        found, unread = text_variants(text, p["name"], lexicon)
        if found:
            persons[i] = _with_also(p, found)
        elif unread and not p.get("also") and p["name"] not in variants_unread:
            variants_unread.append(p["name"])
    return persons, {"uncertain": uncertain, "skipped": skipped, "printed_twice": printed_twice,
                     "variants_unread": variants_unread,
                     "socii_without_names": socii and len(persons) <= len(subjects)}


def _words(s):
    return [fold(w) for w in WORD.findall(s)]


def validate(persons_by_id, footnotes_by_id, current_ids):
    errors = []
    for mrid, persons in persons_by_id.items():
        if mrid not in current_ids:
            errors.append(f"{mrid}: not a current ID")
            continue
        notes = footnotes_by_id.get(mrid, [])
        numbered = {}  # name_key -> the n of each of its persons
        for p in persons:
            n = p.get("n", 1)
            if "n" in p and (type(n) is not int or n < 2):
                errors.append(f"{mrid}: {p['name']!r} has n {n!r}: n is an integer from 2, absent for the first")
                continue
            if "#" in p["name"]:
                errors.append(f"{mrid}: {p['name']!r} contains '#', which separates a person key's n")
            if "also" in p:
                also = p["also"]
                if (not isinstance(also, list) or not also
                        or any(not isinstance(v, str) or not v.strip() or "#" in v
                               or name_key(v) == name_key(p["name"]) for v in also)
                        or len({name_key(v) for v in also}) != len(also)):
                    errors.append(f"{mrid}: {p['name']!r} has a bad also {also!r}: other names, each once, "
                                  "never their own, without '#'")
            numbered.setdefault(name_key(p["name"]), []).append(n)
        for key, ns in numbered.items():
            if sorted(ns) != list(range(1, len(ns) + 1)):
                errors.append(f"{mrid}: the persons named {key!r} are numbered {sorted(ns)}, not 1, 2, 3…")
        for p in persons:
            where = p["where"]
            if where == "text":
                continue
            n = where.get("footnote") if isinstance(where, dict) else None
            if not isinstance(n, int) or not 1 <= n <= len(notes):
                errors.append(f"{mrid}: {p['name']!r} in footnote {n}, which the eulogy does not have")
                continue
            words, name = _words(without_parentheses(notes[n - 1]["text"])), _words(p["name"])
            if not any(words[i:i + len(name)] == name for i in range(len(words))):
                errors.append(f"{mrid}: {p['name']!r} is not printed in footnote {n}")
    return errors


def apply_curated_variants(persons_by_id, curated):
    """Adds data/persons_variants_curated.json ({eulogy: {person key: [names]}}) to the persons'
    `also`, in order and without repeats; it never replaces a eulogy's persons. Returns the errors."""
    errors = []
    for mrid, by_key in curated.items():
        if mrid.startswith("$"):
            continue
        if not isinstance(by_key, dict):
            errors.append(f"{mrid}: expected {{person key: [names]}}")
            continue
        persons = persons_by_id.get(mrid, [])
        for key, names in by_key.items():
            i = next((i for i, p in enumerate(persons) if person_key(p) == key), None)
            if i is None:
                errors.append(f"{mrid}: {key!r} is not a person of this eulogy")
                continue
            if not isinstance(names, list) or not all(
                    isinstance(v, str) and v.strip() and "#" not in v
                    and name_key(v) != name_key(persons[i]["name"]) for v in names):
                errors.append(f"{mrid}: {key!r}: variants must be a list of other names, without '#'")
                continue
            if len({name_key(v) for v in names}) != len(names):
                errors.append(f"{mrid}: {key!r}: a variant is listed twice")
                continue
            # A curated spelling replaces an extracted one of the same name ("Elesbaan" for "Elésbaan").
            curated_keys = {name_key(v) for v in names}
            kept = [v for v in persons[i].get("also", []) if name_key(v) not in curated_keys]
            persons[i] = _with_also({**persons[i], "also": kept}, names)
    return errors


def render_json(persons_by_id):
    doc = {"$comment": COMMENT, "editions": {EDITION: persons_by_id}}
    return json.dumps(doc, ensure_ascii=False, indent=2) + "\n"


def render_report(persons_by_id, issues, noted=frozenset()):
    """Counts and the eulogies to review, by ID: the printed forms are not quoted."""
    total = sum(len(v) for v in persons_by_id.values())
    in_notes = sum(1 for v in persons_by_id.values() for p in v if p["where"] != "text")
    lines = ["# Persons report", "", "Generated by `scripts/extract_persons.py`. Draft pending committee review.", "",
             f"- Eulogies naming someone: {len(persons_by_id)}",
             f"- Persons: {total} ({total - in_notes} in the text, {in_notes} in footnotes)", ""]
    sections = [
        ("Et socii eulogies where no companion was found", [m for m, i in issues.items() if i["socii_without_names"]]),
        ("Eulogies with names in the text not surely read (add a curated entry)",
         [f"{m}: {len(i['uncertain'])}" for m, i in issues.items() if i["uncertain"]]),
        ("Eulogies with footnote segments not read (add a curated entry)",
         [f"{m}: {len(i['skipped'])}" for m, i in issues.items() if i["skipped"]]),
        ("Names printed twice in a row in a footnote list, counted once (probably a misprint: "
         "add a 2004 Latin note in EDITION_NOTES of scripts/extract_registry.py)",
         [f"{m}: {name} ({'noted' if m in noted else 'needs a curator note'})"
          for m, i in issues.items() for name in i.get("printed_twice", [])]),
        ("Persons whose other name (after seu, vel or sive) was not read: add it in "
         "data/persons_variants_curated.json",
         [f"{m}: {name}" for m, i in issues.items() for name in i.get("variants_unread", [])]),
    ]
    for title, items in sections:
        lines += [f"## {title} ({len(items)})", ""] + [f"- {x}" for x in items] + [""]
    return "\n".join(lines)


def _load_footnotes(folder):
    # martyrology-texts' extract_footnotes.py writes footnotes.json with its proofreading
    # (footnotes-overrides.json) already applied.
    return json.loads((folder / "footnotes.json").read_text(encoding="utf-8"))


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    texts_repo = Path(sys.argv[1])
    repo_root = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent
    entries = json.loads((repo_root / "data" / "martyrology_ids.json").read_text(encoding="utf-8"))["entries"]
    current = [e for e in entries if not e.get("deprecated")]
    current.sort(key=lambda e: (e["month"], e["day"], e.get("entry") or 0))
    subjects = json.loads((repo_root / "i18n" / "la.json").read_text(encoding="utf-8"))
    curated_path = repo_root / "data" / "persons_curated.json"
    curated = {k: v for k, v in json.loads(curated_path.read_text(encoding="utf-8")).items()
               if not k.startswith("$")} if curated_path.exists() else {}
    texts = latin_texts(entries, load_texts(texts_repo, EDITION))
    footnotes = _load_footnotes(texts_repo / "data" / "editions" / EDITION)
    lexicon = build_lexicon({e["id"]: subjects.get(e["id"], "") for e in current}, footnotes)
    persons_by_id, issues = {}, {}
    for e in current:
        persons, iss = eulogy_persons(e["id"], subjects.get(e["id"], ""), texts.get(e["id"], ""),
                                      footnotes.get(e["id"], []), lexicon, curated)
        if persons:
            persons_by_id[e["id"]] = persons
        if any(iss.values()):
            issues[e["id"]] = iss
    variants_path = repo_root / "data" / "persons_variants_curated.json"
    curated_variants = json.loads(variants_path.read_text(encoding="utf-8")) if variants_path.exists() else {}
    variant_errors = apply_curated_variants(persons_by_id, curated_variants)
    if variant_errors:
        sys.exit("invalid curated variants:\n" + "\n".join(variant_errors))
    # A variant curated since is no longer unread; a eulogy left without an issue is not listed.
    for mrid, iss in issues.items():
        named = {p["name"] for p in persons_by_id.get(mrid, []) if p.get("also")}
        iss["variants_unread"] = [n for n in iss.get("variants_unread", []) if n not in named]
    issues = {mrid: iss for mrid, iss in issues.items() if any(iss.values())}
    errors = validate(persons_by_id, footnotes, {e["id"] for e in current})
    if errors:
        sys.exit("invalid persons:\n" + "\n".join(errors))
    (repo_root / "data" / "persons.json").write_text(render_json(persons_by_id), encoding="utf-8")
    noted = {e["id"] for e in current if EDITION in (e.get("edition_notes") or {})}
    (repo_root / "docs" / "persons-report.md").write_text(render_report(persons_by_id, issues, noted),
                                                          encoding="utf-8")
    total = sum(len(v) for v in persons_by_id.values())
    print(f"wrote data/persons.json: {total} persons in {len(persons_by_id)} eulogies; {len(issues)} to review")


if __name__ == "__main__":
    main()
