#!/usr/bin/env python3
"""Extract the saints and blessed each current eulogy commemorates (Latin editio altera 2004).

Each person is a Latin nominative name without honorific, with where it is
printed: the eulogy's text, or its nth footnote. Subjects come from
i18n/la.json, companions from the footnote lists and from the names at the
head of the text; data/persons_curated.json replaces a eulogy's extraction.
No text is stored. See docs/superpowers/specs/2026-10-08-persons-design.md.

  data/persons.json          {editions: {edition: {id: [{name, where}]}}}
  docs/persons-report.md     counts and what to review

Usage:
  python3 extract_persons.py /path/to/martyrology-texts [repo_root]

Standard library only.
"""

import json
import sys
from pathlib import Path

from extract_typology import latin_texts, load_texts
from gazetteer_text import fold
from persons_text import WORD, footnote_names, name_key, subject_names, text_companions, without_parentheses

EDITION = "martyrologium_romanum_2004"
COMMENT = ("The saints and blessed each eulogy commemorates, by edition: the Latin nominative name "
           "(honorific-free) and where it is printed, the text or the eulogy's nth footnote. Generated by "
           "scripts/extract_persons.py; see docs/superpowers/specs/2026-10-08-persons-design.md. "
           "Draft pending committee review.")


def build_lexicon(subjects, footnotes):
    """Every word of the known names, by name_key: the vocabulary nominatives are checked against."""
    lex = {}
    names = [n for mrid, s in subjects.items() for n in subject_names(mrid, s)]
    names += [n for notes in footnotes.values() for f in notes for n in footnote_names(f["text"])[0]]
    for n in names:
        for w in n.split():
            if w[:1].isupper():
                lex.setdefault(name_key(w), w)
    return lex


def _same_person(a, b):
    """One name is the other with more words ("Rosalia Clotildis a Sancta Pelagia Bes")."""
    x, y = name_key(a).split(), name_key(b).split()
    n = min(len(x), len(y))
    return n > 0 and x[:n] == y[:n]


def eulogy_persons(mrid, subject, text, footnotes, lexicon, curated):
    if mrid in curated:
        return [dict(p) for p in curated[mrid]], {"uncertain": [], "skipped": [], "socii_without_names": False}
    persons, seen = [], set()
    subjects = subject_names(mrid, subject)

    def add(name, where):
        # A fuller or shorter form of a subject is the subject, in the subject's form.
        if name_key(name) in seen or any(_same_person(name, s) for s in subjects if s != name):
            return
        seen.add(name_key(name))
        persons.append({"name": name, "where": where})

    for n in subjects:
        add(n, "text")
    uncertain, skipped = [], []
    socii = mrid.endswith("-et-socii")
    if socii:
        names, uncertain = text_companions(text or "", lexicon)
        for n in names:
            add(n, "text")
    for i, f in enumerate(footnotes, start=1):
        names, bad = footnote_names(f["text"])
        skipped += bad
        for n in names:
            add(n, {"footnote": i})
    return persons, {"uncertain": uncertain, "skipped": skipped,
                     "socii_without_names": socii and len(persons) <= len(subjects)}


def _words(s):
    return [fold(w) for w in WORD.findall(s)]


def validate(persons_by_id, footnotes_by_id, current_ids):
    errors = []
    for mrid, persons in persons_by_id.items():
        if mrid not in current_ids:
            errors.append(f"{mrid}: not a current ID")
            continue
        notes = footnotes_by_id.get(mrid, [])
        keys = [name_key(p["name"]) for p in persons]
        if len(set(keys)) != len(keys):
            errors.append(f"{mrid}: a name appears twice")
        for p in persons:
            where = p["where"]
            if where == "text":
                continue
            n = where.get("footnote") if isinstance(where, dict) else None
            if not isinstance(n, int) or not 1 <= n <= len(notes):
                errors.append(f"{mrid}: {p['name']!r} in footnote {n}, which the eulogy does not have")
                continue
            words, name = _words(without_parentheses(notes[n - 1]["text"])), _words(p["name"])
            if not any(words[i:i + len(name)] == name for i in range(len(words))):
                errors.append(f"{mrid}: {p['name']!r} is not printed in footnote {n}")
    return errors


def render_json(persons_by_id):
    doc = {"$comment": COMMENT, "editions": {EDITION: persons_by_id}}
    return json.dumps(doc, ensure_ascii=False, indent=2) + "\n"


def render_report(persons_by_id, issues):
    """Counts and the eulogies to review, by ID: the printed forms are not quoted."""
    total = sum(len(v) for v in persons_by_id.values())
    in_notes = sum(1 for v in persons_by_id.values() for p in v if p["where"] != "text")
    lines = ["# Persons report", "", "Generated by `scripts/extract_persons.py`. Draft pending committee review.", "",
             f"- Eulogies naming someone: {len(persons_by_id)}",
             f"- Persons: {total} ({total - in_notes} in the text, {in_notes} in footnotes)", ""]
    sections = [
        ("Et socii eulogies where no companion was found", [m for m, i in issues.items() if i["socii_without_names"]]),
        ("Eulogies with names in the text not surely read (add a curated entry)",
         [f"{m}: {len(i['uncertain'])}" for m, i in issues.items() if i["uncertain"]]),
        ("Eulogies with footnote segments not read (add a curated entry)",
         [f"{m}: {len(i['skipped'])}" for m, i in issues.items() if i["skipped"]]),
    ]
    for title, items in sections:
        lines += [f"## {title} ({len(items)})", ""] + [f"- {x}" for x in items] + [""]
    return "\n".join(lines)


def _load_footnotes(folder):
    # martyrology-texts' extract_footnotes.py writes footnotes.json with its proofreading
    # (footnotes-overrides.json) already applied.
    return json.loads((folder / "footnotes.json").read_text(encoding="utf-8"))


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    texts_repo = Path(sys.argv[1])
    repo_root = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent
    entries = json.loads((repo_root / "data" / "martyrology_ids.json").read_text(encoding="utf-8"))["entries"]
    current = [e for e in entries if not e.get("deprecated")]
    current.sort(key=lambda e: (e["month"], e["day"], e.get("entry") or 0))
    subjects = json.loads((repo_root / "i18n" / "la.json").read_text(encoding="utf-8"))
    curated_path = repo_root / "data" / "persons_curated.json"
    curated = {k: v for k, v in json.loads(curated_path.read_text(encoding="utf-8")).items()
               if not k.startswith("$")} if curated_path.exists() else {}
    texts = latin_texts(entries, load_texts(texts_repo, EDITION))
    footnotes = _load_footnotes(texts_repo / "data" / "editions" / EDITION)
    lexicon = build_lexicon({e["id"]: subjects.get(e["id"], "") for e in current}, footnotes)
    persons_by_id, issues = {}, {}
    for e in current:
        persons, iss = eulogy_persons(e["id"], subjects.get(e["id"], ""), texts.get(e["id"], ""),
                                      footnotes.get(e["id"], []), lexicon, curated)
        if persons:
            persons_by_id[e["id"]] = persons
        if any(iss.values()):
            issues[e["id"]] = iss
    errors = validate(persons_by_id, footnotes, {e["id"] for e in current})
    if errors:
        sys.exit("invalid persons:\n" + "\n".join(errors))
    (repo_root / "data" / "persons.json").write_text(render_json(persons_by_id), encoding="utf-8")
    (repo_root / "docs" / "persons-report.md").write_text(render_report(persons_by_id, issues), encoding="utf-8")
    total = sum(len(v) for v in persons_by_id.values())
    print(f"wrote data/persons.json: {total} persons in {len(persons_by_id)} eulogies; {len(issues)} to review")


if __name__ == "__main__":
    main()
