#!/usr/bin/env python3
"""Gather what the reader's person popups show for each person a mention links to.

For each QID in data/mentions.json: the Wikidata description and the Wikipedia
article title in each interface language, the dates of birth and death with
their precision and whether they are circa, and the portrait (P18) with the
author and license Commons gives it. A portrait whose license Commons does not
state is left out, never shown without its credit. Labels are not gathered:
martyrology-frontend's persons snapshot has them. Needs network access
(cached in .cache/wikidata/).

  data/person_details.json   {"$comment": ..., QID: details}

Usage:
  python3 scripts/person_details.py [repo_root]

Standard library only.
"""

import html
import json
import re
import sys
from pathlib import Path

from wikidata import DETAIL_LANGS, Wikidata, _value, life_date

TAG = re.compile(r"<[^>]+>")
COMMENT = ("What martyrology-frontend's person popups show, by Wikidata item, for each person "
           "data/mentions.json links to: description and Wikipedia title per interface language, "
           "birth and death (year, negative before Christ; precision year, decade or century; circa), and the portrait with its Commons author and "
           "license (null when Commons states no license). Generated by scripts/person_details.py.")


def plain(s):
    """Commons' extmetadata HTML as plain text; None when empty."""
    return " ".join(html.unescape(TAG.sub("", s or "")).split()) or None


def portrait(raw):
    """The item's portrait file (P18), or None."""
    return next((_value(c) for c in raw.get("claims", {}).get("P18", [])
                 if c.get("rank") != "deprecated" and isinstance(_value(c), str)), None)


def image_credit(file, meta):
    """The portrait with its author and license; None when Commons states no license."""
    license_name = plain(meta.get("LicenseShortName", {}).get("value"))
    if not license_name:
        return None
    return {"file": file, "author": plain(meta.get("Artist", {}).get("value")), "license": license_name,
            "license_url": meta.get("LicenseUrl", {}).get("value") or None}


def summarize_details(raw, images):
    claims, descs, links = raw.get("claims", {}), raw.get("descriptions", {}), raw.get("sitelinks", {})
    file = portrait(raw)
    return {
        "description": {lang: descs[lang]["value"] for lang in DETAIL_LANGS if lang in descs},
        "born": life_date(claims, "P569"),
        "died": life_date(claims, "P570"),
        "image": image_credit(file, images[file]) if file in images else None,
        "wikipedia": {lang: links[f"{lang}wiki"]["title"] for lang in DETAIL_LANGS if f"{lang}wiki" in links},
    }


def _qid_number(qid):
    return int(qid[1:])


def person_qids(mentions_doc):
    """The QIDs that person mentions link to, by number."""
    return sorted({m["qid"] for by_id in mentions_doc["editions"].values() for ms in by_id.values() for m in ms
                   if m["kind"] == "person" and m.get("qid")}, key=_qid_number)


def build(client, qids):
    raws = client.details_entities(qids)
    files = sorted({f for f in (portrait(raw) for raw in raws.values()) if f})
    images = client.commons_files(files) if files else {}
    return {q: summarize_details(raws[q], images) for q in qids if q in raws}


def render_json(details):
    doc = {"$comment": COMMENT, **{q: details[q] for q in sorted(details, key=_qid_number)}}
    return json.dumps(doc, ensure_ascii=False, indent=2) + "\n"


def main(argv):
    repo_root = Path(argv[0]) if argv else Path(__file__).resolve().parent.parent
    data = repo_root / "data"
    qids = person_qids(json.loads((data / "mentions.json").read_text(encoding="utf-8")))
    details = build(Wikidata(repo_root / ".cache" / "wikidata"), qids)
    (data / "person_details.json").write_text(render_json(details), encoding="utf-8")
    print(f"wrote data/person_details.json: {len(details)} of {len(qids)} persons; "
          f"{sum(1 for d in details.values() if d['image'])} with a portrait")


if __name__ == "__main__":
    main(sys.argv[1:])
